/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCards: typeof import('./src/components/stats/ActivityCards.vue')['default']
    AddSubscriberDialog: typeof import('./src/components/subscribers/AddSubscriberDialog.vue')['default']
    AppMobileNav: typeof import('./src/components/shell/AppMobileNav.vue')['default']
    AppPageHeader: typeof import('./src/components/shell/AppPageHeader.vue')['default']
    AppSettingsDialog: typeof import('./src/components/settings/AppSettingsDialog.vue')['default']
    AppShell: typeof import('./src/components/shell/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/shell/AppSidebar.vue')['default']
    BlogSettings: typeof import('./src/components/settings/BlogSettings.vue')['default']
    ColumnMappingStep: typeof import('./src/components/subscribers/import/ColumnMappingStep.vue')['default']
    CommentGroup: typeof import('./src/components/blog/CommentGroup.vue')['default']
    CommentRow: typeof import('./src/components/blog/CommentRow.vue')['default']
    CommentToolbar: typeof import('./src/components/blog/CommentToolbar.vue')['default']
    ConfirmEmailSection: typeof import('./src/components/forms/ConfirmEmailSection.vue')['default']
    ConfirmRateCard: typeof import('./src/components/forms/ConfirmRateCard.vue')['default']
    CsvFileStep: typeof import('./src/components/subscribers/import/CsvFileStep.vue')['default']
    DeliveryList: typeof import('./src/components/newsletters/DeliveryList.vue')['default']
    DetailSkeleton: typeof import('./src/components/stats/DetailSkeleton.vue')['default']
    EmailComposer: typeof import('./src/components/email/EmailComposer.vue')['default']
    EmailEditor: typeof import('./src/components/email/EmailEditor.vue')['default']
    EmailPreview: typeof import('./src/components/email/EmailPreview.vue')['default']
    EmailSettings: typeof import('./src/components/settings/EmailSettings.vue')['default']
    EmbedSnippet: typeof import('./src/components/forms/EmbedSnippet.vue')['default']
    EmojiPicker: typeof import('./src/components/EmojiPicker.vue')['default']
    ImportProgressStep: typeof import('./src/components/subscribers/import/ImportProgressStep.vue')['default']
    ImportReviewStep: typeof import('./src/components/subscribers/import/ImportReviewStep.vue')['default']
    ImportSubscribersDialog: typeof import('./src/components/subscribers/import/ImportSubscribersDialog.vue')['default']
    LeadMagnetDownloads: typeof import('./src/components/lead-magnets/LeadMagnetDownloads.vue')['default']
    LeadMagnetFileInput: typeof import('./src/components/lead-magnets/LeadMagnetFileInput.vue')['default']
    ListPagination: typeof import('./src/components/list/ListPagination.vue')['default']
    ListSkeleton: typeof import('./src/components/list/ListSkeleton.vue')['default']
    LMSSyncSettings: typeof import('./src/components/settings/LMSSyncSettings.vue')['default']
    NewFormDialog: typeof import('./src/components/forms/NewFormDialog.vue')['default']
    NewLeadMagnetDialog: typeof import('./src/components/lead-magnets/NewLeadMagnetDialog.vue')['default']
    NewNewsletterDialog: typeof import('./src/components/newsletters/NewNewsletterDialog.vue')['default']
    NewsletterAudience: typeof import('./src/components/newsletters/NewsletterAudience.vue')['default']
    NewsletterEngagement: typeof import('./src/components/newsletters/NewsletterEngagement.vue')['default']
    NewsletterReport: typeof import('./src/components/newsletters/NewsletterReport.vue')['default']
    PublishDialog: typeof import('./src/components/newsletters/PublishDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendNewsletterDialog: typeof import('./src/components/newsletters/SendNewsletterDialog.vue')['default']
    SendTestDialog: typeof import('./src/components/newsletters/SendTestDialog.vue')['default']
    SeriesDialog: typeof import('./src/components/videos/SeriesDialog.vue')['default']
    SeriesSidebar: typeof import('./src/components/videos/SeriesSidebar.vue')['default']
    SeriesStats: typeof import('./src/components/videos/SeriesStats.vue')['default']
    SeriesVideoList: typeof import('./src/components/videos/SeriesVideoList.vue')['default']
    SubscriberEmptyState: typeof import('./src/components/subscribers/SubscriberEmptyState.vue')['default']
    SubscriberFilters: typeof import('./src/components/subscribers/SubscriberFilters.vue')['default']
    SubscriberList: typeof import('./src/components/subscribers/SubscriberList.vue')['default']
    TagPicker: typeof import('./src/components/tags/TagPicker.vue')['default']
    VideoAttachments: typeof import('./src/components/videos/VideoAttachments.vue')['default']
    VideoBoard: typeof import('./src/components/videos/VideoBoard.vue')['default']
    VideoBoardCard: typeof import('./src/components/videos/VideoBoardCard.vue')['default']
    VideoBoardDragPreview: typeof import('./src/components/videos/VideoBoardDragPreview.vue')['default']
    VideoDetails: typeof import('./src/components/videos/VideoDetails.vue')['default']
    VideoStatusDropdown: typeof import('./src/components/videos/VideoStatusDropdown.vue')['default']
    VideoTable: typeof import('./src/components/videos/VideoTable.vue')['default']
    VideoWriting: typeof import('./src/components/videos/VideoWriting.vue')['default']
    WelcomeEmailSection: typeof import('./src/components/forms/WelcomeEmailSection.vue')['default']
  }
}
