/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSubscriberDialog: typeof import('./src/components/subscribers/AddSubscriberDialog.vue')['default']
    AppShell: typeof import('./src/components/shell/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/shell/AppSidebar.vue')['default']
    ColumnMappingStep: typeof import('./src/components/subscribers/import/ColumnMappingStep.vue')['default']
    ConfirmEmailSection: typeof import('./src/components/forms/ConfirmEmailSection.vue')['default']
    CsvFileStep: typeof import('./src/components/subscribers/import/CsvFileStep.vue')['default']
    EmailBodyEditor: typeof import('./src/components/forms/EmailBodyEditor.vue')['default']
    EmailEditor: typeof import('./src/components/newsletters/EmailEditor.vue')['default']
    EmailPreview: typeof import('./src/components/newsletters/EmailPreview.vue')['default']
    EmbedSnippet: typeof import('./src/components/forms/EmbedSnippet.vue')['default']
    ImportProgressStep: typeof import('./src/components/subscribers/import/ImportProgressStep.vue')['default']
    ImportReviewStep: typeof import('./src/components/subscribers/import/ImportReviewStep.vue')['default']
    ImportSubscribersDialog: typeof import('./src/components/subscribers/import/ImportSubscribersDialog.vue')['default']
    LeadMagnetDownloads: typeof import('./src/components/lead-magnets/LeadMagnetDownloads.vue')['default']
    LeadMagnetFileInput: typeof import('./src/components/lead-magnets/LeadMagnetFileInput.vue')['default']
    MailingSettingsDialog: typeof import('./src/components/shell/MailingSettingsDialog.vue')['default']
    NewFormDialog: typeof import('./src/components/forms/NewFormDialog.vue')['default']
    NewLeadMagnetDialog: typeof import('./src/components/lead-magnets/NewLeadMagnetDialog.vue')['default']
    NewNewsletterDialog: typeof import('./src/components/newsletters/NewNewsletterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendTestDialog: typeof import('./src/components/newsletters/SendTestDialog.vue')['default']
    SubscriberEmptyState: typeof import('./src/components/subscribers/SubscriberEmptyState.vue')['default']
    SubscriberFilters: typeof import('./src/components/subscribers/SubscriberFilters.vue')['default']
    SubscriberList: typeof import('./src/components/subscribers/SubscriberList.vue')['default']
    TagPicker: typeof import('./src/components/tags/TagPicker.vue')['default']
    WelcomeEmailSection: typeof import('./src/components/forms/WelcomeEmailSection.vue')['default']
  }
}
